import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://pnmzzgsgmqgzdwsodfla.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBubXp6Z3NnbXFnemR3c29kZmxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ4NDMwNTksImV4cCI6MjEwMDQxOTA1OX0.snxleO0QRoGa832lz49-WMAVs5TcwIJNq6oi2WsEaP4';

const supabase = createClient(supabaseUrl, supabaseKey);

async function createTables() {
  console.log('Attempting to create tables in Supabase...');

  try {
    // Create table: clients
    const clientsSQL = `
      CREATE TABLE IF NOT EXISTS clients (
        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255),
        phone VARCHAR(20),
        address TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
    `;

    // Create table: products
    const productsSQL = `
      CREATE TABLE IF NOT EXISTS products (
        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(255) NOT NULL,
        description TEXT,
        price NUMERIC(10, 2) NOT NULL,
        quantity INT DEFAULT 0,
        sku VARCHAR(100),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
    `;

    // Create table: users (for access control)
    const usersSQL = `
      CREATE TABLE IF NOT EXISTS users (
        id UUID PRIMARY KEY DEFAULT auth.uid(),
        email VARCHAR(255) NOT NULL UNIQUE,
        role VARCHAR(50) DEFAULT 'user',
        active BOOLEAN DEFAULT TRUE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
    `;

    // To execute SQL in Supabase, we need to use the REST API directly
    // Make a fetch request to Supabase SQL API
    const executeSQL = async (sql) => {
      const response = await fetch(`${supabaseUrl}/rest/v1/rpc/execute_sql`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${supabaseKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ query: sql }),
      });

      if (!response.ok) {
        // If the RPC doesn't exist, try another approach
        return null;
      }

      return response.json();
    };

    console.log('⚠️  Note: Tables need to be created through the SQL Editor in Supabase.');
    console.log('');
    console.log('Go to your Supabase project > SQL Editor > New Query');
    console.log('');
    console.log('Paste this SQL:');
    console.log('---');
    console.log(clientsSQL);
    console.log(productsSQL);
    console.log(usersSQL);
    console.log('---');
    console.log('');
    console.log('Execute the query to create the tables.');

  } catch (error) {
    console.error('Error:', error.message);
  }
}

createTables();
